version: "3.9"
services:
  web_a:
    build:
      context: .
    ports:
      - "7004:8081"
    volumes:
      - ./logvolume01:/var/log
  web_b:
    build:
      context: .
    ports:
      - "7005:8081"
    volumes:
      - ./logvolume02:/var/log
  web_c:
    build:
      context: .
    ports:
      - "7006:8081"
    volumes:
      - ./logvolume03:/var/log
volumes:
  logvolume01: {}